---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: Install Ubuntu desktop packages
    apt:
      name: ubuntu-desktop
      state: present

